name: PDF to Text Conversion

on:
  workflow_dispatch:
    inputs:
      pdf_path:
        description: 'Path to the PDF file'
        required: true
      txt_path:
        description: 'Path to save the text file'
        required: true

jobs:
  convert_pdf:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdfplumber

    - name: Create output directory
      run: mkdir -p $(dirname ${{ github.event.inputs.txt_path }})

    - name: Convert PDF to Text
      run: |
        python pdf_to_text.py ${{ github.event.inputs.pdf_path }} ${{ github.event.inputs.txt_path }}
      env:
        GITHUB_WORKSPACE: ${{ github.workspace }}

    - name: Commit text file
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add ${{ github.event.inputs.txt_path }}
        git commit -m "Add converted text file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Remove uploaded PDF file
      run: |
        if [ -f ${{ github.workspace }}/${{ github.event.inputs.pdf_path }} ]; then
          echo "Removing file: ${{ github.workspace }}/${{ github.event.inputs.pdf_path }}"
          rm ${{ github.workspace }}/${{ github.event.inputs.pdf_path }}
        else
          echo "File does not exist: ${{ github.workspace }}/${{ github.event.inputs.pdf_path }}"
        fi

