name: convert_pdf

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install pdfplumber
      run: |
        python -m pip install --upgrade pip
        pip install pdfplumber

    - name: Find PDF file
      id: find_pdf
      run: |
        pdf_file=$(find path/to/uploaded -name "*.pdf" | head -n 1)
        echo "PDF_FILE=$pdf_file" >> $GITHUB_ENV

    - name: Create output directory
      run: mkdir -p path/to/output

    - name: Convert PDF to text
      run: |
        pdf_file=$(echo ${{ env.PDF_FILE }})
        base_name=$(basename "$pdf_file" .pdf)
        python pdf_to_text.py "$pdf_file" "path/to/output/$base_name.txt"

    - name: Commit and push converted text file
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add path/to/output/*.txt
        git commit -m "Add converted text file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
